export { isSSR } from './is-ssr';
export { haptic } from './haptic';
export { useControlled } from './use-controlled';
export { useReducedMotion } from './use-reduced-motion';
export { useAnimationLoop } from './use-animation-loop';
export type { AnimationLoopOptions } from './use-animation-loop';
export { useLatestRef } from './use-latest-ref';
export { useGameScale } from './use-game-scale';
export type { UseGameScaleOptions } from './use-game-scale';
export { resolveLocalized } from './i18n-utils';
export type { LocalizableText } from './i18n-utils';
export { pickPrize } from './use-prize';
export { GAME_STATES, canTransition, isTerminal } from './state-machine';
export { StateBadge } from './state-badge';
export type { StateBadgeProps } from './state-badge';
export { Confetti } from './confetti';
export type { ConfettiProps } from './confetti';
export { Button } from './button';
export type { ButtonProps, ButtonVariant, ButtonSize } from './button';
export type { GameState, Prize, BaseGameProps, ControlledStateProps } from './types';
